### ISSUE TITLE
Error: none of the options work

### ISSUE THREAD

**Issue by Felina-Lain** [Weisl/simple_renaming_panel#63]
Hello, I tried using the panel, but when I use rename, or search and select, or search and replace I just constantly get

Traceback (most recent call last):
  File "C:\Users\Felina\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\simple_renaming_panel\renaming_operators.py", line 349, in execute
    replaceName = VariableReplacer.replaceInputString(context, wm.renaming_newName, entity)
  File "C:\Users\Felina\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\simple_renaming_panel\renaming_operators.py", line 62, in replaceInputString
    inputText = re.sub(r'@a', cls.getActive(context), inputText)  # active object
  File "C:\Users\Felina\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\simple_renaming_panel\renaming_operators.py", line 152, in getActive
    return context.object.name
AttributeError: 'NoneType' object has no attribute 'name'

location: <unknown location>:-1

using blender 2.83.1

**Comment by Weisl** [comment]
Thanks for reporting. I will look into this. I do already have an idea what could cause it

**Comment by Weisl** [comment]
This bug should be fixed. If you download the latest version from github or synch the master branch from the addon updater it should work. 
The issue occured when no active object existed :)
